from pathlib import Path
import shutil, re, zipfile, os

ROOT=Path(__file__).resolve().parents[2]
SRC=ROOT/'egediagnostik_web'
DIST=ROOT/'build_full_php'/'egediagnostik'
ZIP=ROOT/'EGE_Diagnostik_FULL_PHP_Server.zip'
if DIST.parent.exists(): shutil.rmtree(DIST.parent)
DIST.parent.mkdir(parents=True)
shutil.copytree(SRC,DIST,ignore=shutil.ignore_patterns('api','lib','database','package.json','vercel.json','README.md'))
(DIST/'api').mkdir(exist_ok=True)
(DIST/'config').mkdir(exist_ok=True)

# IIS alt klasörde (/egediagnostik/) çalışması için site içi mutlak yolları göreli yap.
for p in DIST.rglob('*'):
    if not p.is_file() or p.suffix.lower() not in {'.html','.js','.css'}: continue
    s=p.read_text(encoding='utf-8')
    s=s.replace('href="/','href="./').replace("href='/","href='./")
    s=s.replace('src="/','src="./').replace("src='/","src='./")
    s=s.replace("location.href='/","location.href='./").replace('location.href="/','location.href="./')
    s=s.replace("location.assign('/","location.assign('./").replace("location.replace('/","location.replace('./")
    s=s.replace("fetch('/api/","fetch('./api/").replace('fetch("/api/','fetch("./api/')
    s=s.replace("api('/api/","api('./api/").replace('api("/api/','api("./api/')
    s=s.replace("href='/certificate-admin.html'","href='./certificate-admin.html'")
    p.write_text(s,encoding='utf-8')

# Sertifika bağlantısını admin HTML'e doğrudan ekle; JS enjeksiyonuna bağımlı kalmasın.
admin=DIST/'admin.html'
if admin.exists():
    s=admin.read_text(encoding='utf-8')
    if 'data-certificate-center' not in s:
        needle='<button class="side-link" data-section="results"><span class="side-icon">◎</span>Sonuçlar</button>'
        repl=needle+'<a class="side-link" href="./certificate-admin.html" data-certificate-center="1"><span class="side-icon">◆</span>Sertifika Tasarımı</a>'
        s=s.replace(needle,repl)
    if 'certificate-admin-entry.js' not in s:
        s=s.replace('</body>','<script src="./assets/certificate-admin-entry.js"></script></body>')
    admin.write_text(s,encoding='utf-8')

bootstrap=r'''<?php
declare(strict_types=1);
$cfgFile=__DIR__.'/config.php';
if(!file_exists($cfgFile)){http_response_code(503);header('Content-Type: application/json; charset=utf-8');echo json_encode(['error'=>'not_installed','message'=>'Önce install.php çalıştırın.'],JSON_UNESCAPED_UNICODE);exit;}
$config=require $cfgFile; date_default_timezone_set($config['app']['timezone']??'Europe/Istanbul');
if(session_status()!==PHP_SESSION_ACTIVE){session_name($config['app']['session_name']??'ege_session');session_set_cookie_params(['httponly'=>true,'secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','samesite'=>'Lax','path'=>'/']);session_start();}
function db():PDO{static $p=null;global $config;if($p)return $p;$d=$config['db'];$p=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$d['name']};charset=utf8mb4",$d['user'],$d['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);return $p;}
function inp():array{$r=file_get_contents('php://input');$j=$r?json_decode($r,true):null;return is_array($j)?$j:($_POST?:[]);}function out($d,$s=200):never{http_response_code($s);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function user():?array{if(empty($_SESSION['uid']))return null;$q=db()->prepare("SELECT u.id,u.role_id,u.first_name,u.last_name,u.email,u.phone,u.institution,u.status,r.slug role,r.name role_name FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=?");$q->execute([$_SESSION['uid']]);return $q->fetch()?:null;}
function need($role=null):array{$u=user();if(!$u||$u['status']!=='active')out(['error'=>'unauthorized'],401);if($role&&$u['role']!==$role)out(['error'=>'forbidden'],403);return $u;}
function certcode(){return 'EGE-'.date('Y').'-'.strtoupper(substr(bin2hex(random_bytes(6)),0,10));}
function activeTemplate(){return db()->query("SELECT * FROM certificate_templates WHERE is_active=1 ORDER BY id DESC LIMIT 1")->fetch()?:null;}
'''
(DIST/'config'/'bootstrap.php').write_text(bootstrap,encoding='utf-8')

sql=r'''CREATE TABLE IF NOT EXISTS roles(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,slug VARCHAR(50) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,role_id INT NOT NULL,first_name VARCHAR(100) NOT NULL,last_name VARCHAR(100) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,phone VARCHAR(40),institution VARCHAR(190),status ENUM('active','passive','blocked') NOT NULL DEFAULT 'active',last_login_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(role_id) REFERENCES roles(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS courses(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(220) NOT NULL,slug VARCHAR(230) NOT NULL UNIQUE,summary TEXT,level VARCHAR(50),duration_minutes INT DEFAULT 0,is_active TINYINT(1) DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS course_sections(id INT AUTO_INCREMENT PRIMARY KEY,course_id INT NOT NULL,title VARCHAR(220) NOT NULL,sort_order INT DEFAULT 0,FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS lessons(id INT AUTO_INCREMENT PRIMARY KEY,section_id INT NOT NULL,title VARCHAR(220) NOT NULL,content MEDIUMTEXT,video_type VARCHAR(30) DEFAULT 'none',video_url VARCHAR(2000),duration_seconds INT DEFAULT 0,sort_order INT DEFAULT 0,is_active TINYINT(1) DEFAULT 1,FOREIGN KEY(section_id) REFERENCES course_sections(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS exams(id INT AUTO_INCREMENT PRIMARY KEY,course_id INT NOT NULL,title VARCHAR(220) NOT NULL,question_count INT DEFAULT 10,pass_score DECIMAL(5,2) DEFAULT 70,time_limit_minutes INT DEFAULT 20,max_attempts INT DEFAULT 3,is_active TINYINT(1) DEFAULT 1,FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS exam_questions(id INT AUTO_INCREMENT PRIMARY KEY,exam_id INT NOT NULL,question_text TEXT NOT NULL,option_a TEXT NOT NULL,option_b TEXT NOT NULL,option_c TEXT NOT NULL,option_d TEXT NOT NULL,correct_option ENUM('A','B','C','D') NOT NULL,explanation TEXT,is_active TINYINT(1) DEFAULT 1,FOREIGN KEY(exam_id) REFERENCES exams(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS exam_attempts(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,exam_id INT NOT NULL,score DECIMAL(5,2) NOT NULL,passed TINYINT(1) NOT NULL,started_at DATETIME NOT NULL,completed_at DATETIME NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(exam_id) REFERENCES exams(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS certificate_templates(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,title VARCHAR(200) NOT NULL,body_template LONGTEXT NOT NULL,theme VARCHAR(50) DEFAULT 'corporate',accent VARCHAR(20) DEFAULT '#0878d1',background_url VARCHAR(2000),footer_text VARCHAR(1000),signature_name VARCHAR(160),signature_title VARCHAR(160),is_default TINYINT(1) DEFAULT 0,is_active TINYINT(1) DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS certificates(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,course_id INT NOT NULL,exam_attempt_id INT,template_id INT,certificate_code VARCHAR(80) NOT NULL UNIQUE,score DECIMAL(5,2) NOT NULL,template_snapshot LONGTEXT,issued_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_user_course(user_id,course_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE,FOREIGN KEY(template_id) REFERENCES certificate_templates(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS site_settings(setting_key VARCHAR(150) PRIMARY KEY,setting_value LONGTEXT,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;'''
(DIST/'database.sql').write_text(sql,encoding='utf-8')

installer=r'''<?php
$error='';$ok='';if($_SERVER['REQUEST_METHOD']==='POST'){try{$h=trim($_POST['host']);$port=(int)$_POST['port'];$n=preg_replace('/[^a-zA-Z0-9_]/','',$_POST['name']);$u=trim($_POST['user']);$p=$_POST['pass'];$ae=trim($_POST['admin_email']);$ap=$_POST['admin_pass'];$pdo=new PDO("mysql:host=$h;port=$port;charset=utf8mb4",$u,$p,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$pdo->exec("CREATE DATABASE IF NOT EXISTS `$n` CHARACTER SET utf8mb4 COLLATE utf8mb4_turkish_ci");$pdo->exec("USE `$n`");foreach(array_filter(array_map('trim',preg_split('/;\\s*(?:\\r?\\n|$)/',file_get_contents(__DIR__.'/database.sql')))) as $q)$pdo->exec($q);$pdo->exec("INSERT IGNORE INTO roles(id,name,slug) VALUES(1,'Sistem Yöneticisi','admin'),(2,'Eğitim Kullanıcısı','student')");$q=$pdo->prepare("INSERT INTO users(role_id,first_name,last_name,email,password_hash,institution,status) VALUES(1,'EGE','Yönetici',?,?, 'EGE Diagnostik','active') ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash),role_id=1,status='active'");$q->execute([$ae,password_hash($ap,PASSWORD_DEFAULT)]);$pdo->exec("INSERT IGNORE INTO courses(id,title,slug,summary,level,duration_minutes,is_active) VALUES(1,'Doğru Sonuç ve Kalite Temelleri','dogru-sonuc-kalite','Kurulum, validasyon, kalibrasyon ve kalite yaklaşımı.','Temel',55,1)");$pdo->exec("INSERT IGNORE INTO exams(id,course_id,title,question_count,pass_score,time_limit_minutes,max_attempts,is_active) VALUES(1,1,'Doğru Sonuç Temel Değerlendirme',3,70,10,3,1)");$body=json_encode(['text'=>'{{full_name}}, {{course_title}} eğitim programını %{{score}} başarıyla tamamlamıştır.','theme'=>'corporate','accent'=>'#0878d1','footer'=>'Başarılarının devamını dileriz.','signature_name'=>'EGE Diagnostik Eğitim Kurulu','signature_title'=>'Eğitim Direktörlüğü'],JSON_UNESCAPED_UNICODE);$q=$pdo->prepare("INSERT IGNORE INTO certificate_templates(id,name,title,body_template,theme,accent,is_default,is_active) VALUES(1,'Kurumsal Mavi','BAŞARI SERTİFİKASI',?,'corporate','#0878d1',1,1)");$q->execute([$body]);$cfg="<?php\\nreturn ".var_export(['db'=>['host'=>$h,'port'=>$port,'name'=>$n,'user'=>$u,'pass'=>$p],'app'=>['session_name'=>'ege_session','timezone'=>'Europe/Istanbul']],true).";\\n";file_put_contents(__DIR__.'/config/config.php',$cfg);$ok='Kurulum tamamlandı. install.php dosyasını güvenlik için silin.';}catch(Throwable $e){$error=$e->getMessage();}}
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EGE Diagnostik Kurulum</title><link rel="stylesheet" href="./assets/login.css"></head><body class="login-page"><main class="login-card" style="max-width:760px;margin:5vh auto;padding:30px"><h1>FULL PHP Server Kurulumu</h1><?php if($error):?><p><?=htmlspecialchars($error)?></p><?php endif;?><?php if($ok):?><p><?=htmlspecialchars($ok)?></p><a href="./login.html">Portal Girişi</a><?php else:?><form method="post" style="display:grid;gap:12px"><input name="host" value="127.0.0.1" placeholder="MySQL Host" required><input name="port" value="3306" required><input name="name" value="egediagnostik" required><input name="user" value="root" placeholder="MySQL Kullanıcı" required><input type="password" name="pass" placeholder="MySQL Parola"><input type="email" name="admin_email" value="admin@egediagnostik.com.tr" required><input type="password" name="admin_pass" minlength="10" placeholder="Admin Parola" required><button type="submit">Kurulumu Başlat</button></form><?php endif;?></main></body></html>'''
(DIST/'install.php').write_text(installer,encoding='utf-8')

router=r'''<?php
require __DIR__.'/../config/bootstrap.php';$route=trim($_GET['route']??'','/');$m=$_SERVER['REQUEST_METHOD'];$in=inp();
if($route==='health')out(['ok'=>true,'mode'=>'php-mysql','database_ready'=>true]);
if($route==='login'&&$m==='POST'){$q=db()->prepare("SELECT u.*,r.slug role FROM users u JOIN roles r ON r.id=u.role_id WHERE u.email=?");$q->execute([strtolower(trim($in['email']??''))]);$u=$q->fetch();if(!$u||$u['status']!=='active'||!password_verify($in['password']??'',$u['password_hash']))out(['error'=>'invalid_credentials'],401);$_SESSION['uid']=$u['id'];db()->prepare("UPDATE users SET last_login_at=NOW() WHERE id=?")->execute([$u['id']]);out(['ok'=>true,'redirect'=>$u['role']==='admin'?'./admin.html':'./academy.html']);}
if(in_array($route,['me','session'],true)){$u=need();out(['ok'=>true,'demo'=>false,'user'=>['id'=>$u['id'],'name'=>$u['first_name'].' '.$u['last_name'],'role'=>$u['role'],'email'=>$u['email'],'institution'=>$u['institution']]]);}if($route==='logout'){session_destroy();out(['ok'=>true]);}
if($route==='admin/users'){need('admin');if($m==='GET'){$it=db()->query("SELECT u.*,r.name role_name,r.slug role_slug FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.id DESC")->fetchAll();foreach($it as &$x)$x['roles']=['name'=>$x['role_name'],'slug'=>$x['role_slug']];out(['items'=>$it,'roles'=>db()->query("SELECT id,name,slug FROM roles")->fetchAll()]);}if($m==='POST'){$id=(int)($in['id']??0);$a=[(int)($in['role_id']??2),$in['first_name'],$in['last_name'],$in['email'],$in['phone']??null,$in['institution']??null,$in['status']??'active'];if($id){$sql="UPDATE users SET role_id=?,first_name=?,last_name=?,email=?,phone=?,institution=?,status=?";if(!empty($in['password'])){$sql.=",password_hash=?";$a[]=password_hash($in['password'],PASSWORD_DEFAULT);}$sql.=" WHERE id=?";$a[]=$id;db()->prepare($sql)->execute($a);}else{if(empty($in['password']))out(['error'=>'password_required'],400);$a[]=password_hash($in['password'],PASSWORD_DEFAULT);db()->prepare("INSERT INTO users(role_id,first_name,last_name,email,phone,institution,status,password_hash) VALUES(?,?,?,?,?,?,?,?)")->execute($a);}out(['ok'=>true]);}if($m==='DELETE'){db()->prepare("DELETE FROM users WHERE id=?")->execute([(int)($_GET['id']??0)]);out(['ok'=>true]);}}
if($route==='admin/courses'){need('admin');if($m==='GET')out(['items'=>db()->query("SELECT * FROM courses ORDER BY id DESC")->fetchAll()]);if($m==='POST'){$id=(int)($in['id']??0);$a=[$in['title'],$in['slug'],$in['summary']??null,$in['level']??null,(int)($in['duration_minutes']??0),!empty($in['is_active'])?1:0];if($id){$a[]=$id;db()->prepare("UPDATE courses SET title=?,slug=?,summary=?,level=?,duration_minutes=?,is_active=? WHERE id=?")->execute($a);}else db()->prepare("INSERT INTO courses(title,slug,summary,level,duration_minutes,is_active) VALUES(?,?,?,?,?,?)")->execute($a);out(['ok'=>true]);}if($m==='DELETE'){db()->prepare("DELETE FROM courses WHERE id=?")->execute([(int)($_GET['id']??0)]);out(['ok'=>true]);}}
if($route==='learning'){$u=need();$cid=(int)($_GET['course_id']??0);if($m==='GET'){if(!$cid)out(['items'=>db()->query("SELECT * FROM courses WHERE is_active=1")->fetchAll()]);$q=db()->prepare("SELECT * FROM course_sections WHERE course_id=? ORDER BY sort_order,id");$q->execute([$cid]);$ss=$q->fetchAll();foreach($ss as &$s){$q2=db()->prepare("SELECT * FROM lessons WHERE section_id=? ORDER BY sort_order,id");$q2->execute([$s['id']]);$s['lessons']=$q2->fetchAll();}out(['sections'=>$ss]);}if($m==='POST'){need('admin');$a=$in['action']??'';if($a==='upsert_section'){$id=(int)($in['id']??0);if($id)db()->prepare("UPDATE course_sections SET title=?,sort_order=? WHERE id=?")->execute([$in['title'],(int)$in['sort_order'],$id]);else db()->prepare("INSERT INTO course_sections(course_id,title,sort_order) VALUES(?,?,?)")->execute([(int)$in['course_id'],$in['title'],(int)$in['sort_order']]);out(['ok'=>true]);}if($a==='delete_section'){db()->prepare("DELETE FROM course_sections WHERE id=?")->execute([(int)$in['id']]);out(['ok'=>true]);}if($a==='upsert_lesson'){$id=(int)($in['id']??0);$v=[(int)$in['section_id'],$in['title'],$in['content']??null,$in['video_type']??'none',$in['video_url']??null,(int)($in['duration_seconds']??0),(int)($in['sort_order']??0),!empty($in['is_active'])?1:0];if($id){$v[]=$id;db()->prepare("UPDATE lessons SET section_id=?,title=?,content=?,video_type=?,video_url=?,duration_seconds=?,sort_order=?,is_active=? WHERE id=?")->execute($v);}else db()->prepare("INSERT INTO lessons(section_id,title,content,video_type,video_url,duration_seconds,sort_order,is_active) VALUES(?,?,?,?,?,?,?,?)")->execute($v);out(['ok'=>true]);}if($a==='delete_lesson'){db()->prepare("DELETE FROM lessons WHERE id=?")->execute([(int)$in['id']]);out(['ok'=>true]);}}}
if($route==='admin/exams'){need('admin');if($m==='GET')out(['items'=>db()->query("SELECT e.*,c.title course_title FROM exams e JOIN courses c ON c.id=e.course_id ORDER BY e.id DESC")->fetchAll()]);if($m==='POST'){$id=(int)($in['id']??0);$a=[(int)$in['course_id'],$in['title'],(int)$in['question_count'],(float)$in['pass_score'],(int)$in['time_limit_minutes'],(int)$in['max_attempts'],!empty($in['is_active'])?1:0];if($id){$a[]=$id;db()->prepare("UPDATE exams SET course_id=?,title=?,question_count=?,pass_score=?,time_limit_minutes=?,max_attempts=?,is_active=? WHERE id=?")->execute($a);}else db()->prepare("INSERT INTO exams(course_id,title,question_count,pass_score,time_limit_minutes,max_attempts,is_active) VALUES(?,?,?,?,?,?,?)")->execute($a);out(['ok'=>true]);}if($m==='DELETE'){db()->prepare("DELETE FROM exams WHERE id=?")->execute([(int)($_GET['id']??0)]);out(['ok'=>true]);}}
if($route==='admin/questions'){need('admin');if($m==='GET'){$e=(int)($_GET['exam_id']??0);$q=db()->prepare("SELECT * FROM exam_questions WHERE (?=0 OR exam_id=?) ORDER BY id");$q->execute([$e,$e]);out(['items'=>$q->fetchAll()]);}if($m==='POST'){$id=(int)($in['id']??0);$a=[(int)$in['exam_id'],$in['question_text'],$in['option_a'],$in['option_b'],$in['option_c'],$in['option_d'],$in['correct_option'],$in['explanation']??null,!empty($in['is_active'])?1:0];if($id){$a[]=$id;db()->prepare("UPDATE exam_questions SET exam_id=?,question_text=?,option_a=?,option_b=?,option_c=?,option_d=?,correct_option=?,explanation=?,is_active=? WHERE id=?")->execute($a);}else db()->prepare("INSERT INTO exam_questions(exam_id,question_text,option_a,option_b,option_c,option_d,correct_option,explanation,is_active) VALUES(?,?,?,?,?,?,?,?,?)")->execute($a);out(['ok'=>true]);}if($m==='DELETE'){db()->prepare("DELETE FROM exam_questions WHERE id=?")->execute([(int)($_GET['id']??0)]);out(['ok'=>true]);}}
if($route==='admin/results'){need('admin');out(['items'=>db()->query("SELECT a.*,CONCAT(u.first_name,' ',u.last_name) user_name,e.title exam_title,c.title course_title FROM exam_attempts a JOIN users u ON u.id=a.user_id JOIN exams e ON e.id=a.exam_id JOIN courses c ON c.id=e.course_id ORDER BY a.id DESC")->fetchAll()]);}
if($route==='exams'){$u=need();if(isset($_GET['id'])){$id=(int)$_GET['id'];$q=db()->prepare("SELECT * FROM exams WHERE id=? AND is_active=1");$q->execute([$id]);$e=$q->fetch();$q=db()->prepare("SELECT id,question_text,option_a,option_b,option_c,option_d FROM exam_questions WHERE exam_id=? AND is_active=1 ORDER BY id LIMIT ".(int)$e['question_count']);$q->execute([$id]);out(['exam'=>$e,'questions'=>$q->fetchAll()]);}out(['items'=>db()->query("SELECT e.*,c.title course_title FROM exams e JOIN courses c ON c.id=e.course_id WHERE e.is_active=1")->fetchAll()]);}
if($route==='submit-exam'&&$m==='POST'){$u=need();$eid=(int)$in['exam_id'];$q=db()->prepare("SELECT * FROM exams WHERE id=?");$q->execute([$eid]);$e=$q->fetch();$q=db()->prepare("SELECT id,correct_option FROM exam_questions WHERE exam_id=? AND is_active=1 ORDER BY id LIMIT ".(int)$e['question_count']);$q->execute([$eid]);$qs=$q->fetchAll();if(!$qs)out(['error'=>'exam_has_no_questions'],400);$ok=0;foreach($qs as $x)if(($in['answers'][(string)$x['id']]??null)===$x['correct_option'])$ok++;$score=round($ok/count($qs)*100,2);$passed=$score>=(float)$e['pass_score'];db()->prepare("INSERT INTO exam_attempts(user_id,exam_id,score,passed,started_at,completed_at) VALUES(?,?,?,?,NOW(),NOW())")->execute([$u['id'],$eid,$score,$passed?1:0]);$aid=(int)db()->lastInsertId();$cert=null;if($passed){$t=activeTemplate();$q=db()->prepare("SELECT * FROM certificates WHERE user_id=? AND course_id=?");$q->execute([$u['id'],$e['course_id']]);$cert=$q->fetch();if(!$cert){$code=certcode();db()->prepare("INSERT INTO certificates(user_id,course_id,exam_attempt_id,template_id,certificate_code,score,template_snapshot) VALUES(?,?,?,?,?,?,?)")->execute([$u['id'],$e['course_id'],$aid,$t['id']??null,$code,$score,$t?json_encode($t,JSON_UNESCAPED_UNICODE):null]);$cert=['certificate_code'=>$code,'score'=>$score];}}out(['score'=>$score,'passed'=>$passed,'correct'=>$ok,'total'=>count($qs),'certificate'=>$cert]);}
if($route==='certificates'){$u=need();$q=db()->prepare("SELECT c.*,co.title course_title,CONCAT(u.first_name,' ',u.last_name) full_name,u.institution FROM certificates c JOIN courses co ON co.id=c.course_id JOIN users u ON u.id=c.user_id WHERE c.user_id=? ORDER BY c.id DESC");$q->execute([$u['id']]);out(['items'=>$q->fetchAll()]);}
if($route==='admin/certificate-center'){need('admin');if($m==='GET'){if(($_GET['action']??'')==='issued')out(['items'=>db()->query("SELECT c.*,CONCAT(u.first_name,' ',u.last_name) full_name,u.email,u.institution,co.title course_title FROM certificates c JOIN users u ON u.id=c.user_id JOIN courses co ON co.id=c.course_id ORDER BY c.id DESC")->fetchAll()]);out(['items'=>db()->query("SELECT * FROM certificate_templates ORDER BY is_active DESC,id DESC")->fetchAll()]);}if($m==='POST'){if(($in['action']??'')==='activate'){$id=(int)$in['id'];db()->beginTransaction();db()->exec("UPDATE certificate_templates SET is_active=0,is_default=0");db()->prepare("UPDATE certificate_templates SET is_active=1,is_default=1 WHERE id=?")->execute([$id]);db()->commit();out(['ok'=>true]);}$id=(int)($in['id']??0);$body=$in['body_template']??$in['body']??'{}';$a=[$in['name'],$in['title'],$body,$in['theme']??'corporate',$in['accent']??'#0878d1',$in['background_url']??null,$in['footer_text']??null,$in['signature_name']??null,$in['signature_title']??null];if($id){$a[]=$id;db()->prepare("UPDATE certificate_templates SET name=?,title=?,body_template=?,theme=?,accent=?,background_url=?,footer_text=?,signature_name=?,signature_title=? WHERE id=?")->execute($a);}else db()->prepare("INSERT INTO certificate_templates(name,title,body_template,theme,accent,background_url,footer_text,signature_name,signature_title) VALUES(?,?,?,?,?,?,?,?,?)")->execute($a);out(['ok'=>true]);}if($m==='DELETE'){$id=(int)($_GET['id']??0);$q=db()->prepare("SELECT is_active FROM certificate_templates WHERE id=?");$q->execute([$id]);$t=$q->fetch();if($t&&$t['is_active'])out(['error'=>'active_template_cannot_be_deleted'],400);db()->prepare("DELETE FROM certificate_templates WHERE id=?")->execute([$id]);out(['ok'=>true]);}}
if($route==='contact'&&$m==='POST')out(['ok'=>true,'message'=>'Mesaj alındı.']);out(['error'=>'not_found','route'=>$route],404);'''
(DIST/'api'/'index.php').write_text(router,encoding='utf-8')

web=r'''<?xml version="1.0" encoding="UTF-8"?><configuration><system.webServer><defaultDocument enabled="true"><files><clear/><add value="index.html"/></files></defaultDocument><rewrite><rules><rule name="PHP API Router" stopProcessing="true"><match url="^api/(.*)$"/><action type="Rewrite" url="api/index.php?route={R:1}" appendQueryString="true"/></rule></rules></rewrite><httpProtocol><customHeaders><add name="X-Content-Type-Options" value="nosniff"/><add name="X-Frame-Options" value="SAMEORIGIN"/><add name="Referrer-Policy" value="strict-origin-when-cross-origin"/></customHeaders></httpProtocol></system.webServer></configuration>'''
(DIST/'web.config').write_text(web,encoding='utf-8')

readme='''EGE DIAGNOSTIK FULL PHP SERVER\n===============================\nBu paket GitHub'daki canlı tasarım dosyalarının tamamını korur ve PHP+MySQL backend ekler.\n\nIIS: PHP 8.2/8.3 FastCGI + PDO MySQL + URL Rewrite Module gerekir.\n1) ZIP'i IIS altındaki egediagnostik klasörüne çıkarın.\n2) http://SUNUCU/egediagnostik/install.php açın.\n3) MySQL bilgileri ve admin parolasını girin.\n4) Kurulum sonrası install.php dosyasını silin.\n5) Ana site: /egediagnostik/\n6) Portal: /egediagnostik/login.html\n7) Admin: /egediagnostik/admin.html\n8) Sertifika: /egediagnostik/certificate-admin.html\n\nAdmin navbarında Sonuçlar altında Sertifika Tasarımı kalıcıdır.\n'''
(DIST/'README-FULL-PHP.txt').write_text(readme,encoding='utf-8')
if ZIP.exists(): ZIP.unlink()
with zipfile.ZipFile(ZIP,'w',zipfile.ZIP_DEFLATED) as z:
    for p in DIST.rglob('*'):
        if p.is_file(): z.write(p,p.relative_to(DIST))
print(ZIP)
